# Generated by Django 3.2 on 2021-12-01 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20211201_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='MISSION', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MissionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
                ('ourmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.ourmission')),
            ],
        ),
    ]
