# Generated by Django 3.2 on 2021-12-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_missioncontent_ourmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchcontent',
            name='ourbelief',
        ),
        migrations.DeleteModel(
            name='OurChurch',
        ),
        migrations.DeleteModel(
            name='ChurchContent',
        ),
    ]
