# Generated by Django 3.2 on 2021-12-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_churchcontent_ourchurch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethods',
            options={'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterModelOptions(
            name='sliders',
            options={'verbose_name_plural': 'Home Page Sliders'},
        ),
    ]
