# Generated by Django 3.2 on 2021-12-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_publications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourgroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Enter the Depart Name', max_length=300)),
                ('phone_number', models.CharField(max_length=13)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PastorAndWifeDetailAtFrontPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastor_image', models.ImageField(blank=True, upload_to='PastorAndWifeDetailAtFrontPage/pastor_image/')),
                ('pastor_wife_image', models.ImageField(blank=True, upload_to='PastorAndWifeDetailAtFrontPage/pastor_wife_image/')),
                ('content', models.TextField()),
                ('header', models.CharField(default='Mr and Miss Anthony Aro', max_length=200)),
            ],
        ),
    ]
