# Generated by Django 3.2 on 2021-12-17 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_ourgroups_pastorandwifedetailatfrontpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='beliefcontent',
            name='heading',
            field=models.CharField(default='..title', max_length=400),
        ),
        migrations.CreateModel(
            name='SermonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.sermon')),
            ],
        ),
    ]
